# Generated by Django 3.2.9 on 2021-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20211215_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
