# Generated by Django 3.2.9 on 2021-12-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
